# Generated by Django 3.1.5 on 2021-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User name')),
                ('email', models.CharField(max_length=50, verbose_name='User email')),
                ('password', models.CharField(max_length=20, verbose_name='User Password')),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
