# Generated by Django 3.1.5 on 2021-04-04 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('date_comment', models.DateField(default=datetime.date.today)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_app.blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_app.user')),
            ],
        ),
    ]
