# Generated by Django 3.1.5 on 2021-04-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
