# Generated by Django 3.1.5 on 2021-04-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0006_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Coment',
        ),
    ]
